title: Liefery IT Legacy Blog
description: > # this means to ignore newlines until "baseurl:"
  The legacy blog of the Liefery IT team
baseurl: "/blog"
url: "https://liefery-it-legacy.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: [Guardfile, invoker.ini, Gemfile, Gemfile.lock, README.md]
plugins:
  - jemoji
  - jekyll-feed

paginate: 5

feed:
  path: feed.xml
